[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
axum = "0.7.5"


[dev-dependencies]
anyhow = "1.0.81"
